### PR TITLE
add codecov 

### PR DESCRIPTION
**Pull request by steven2249**
I am an rOpensci intern, working on adding test coverage components.

### CODE REVIEW

**Comment by sckott** [comment]
@steven2249 i assume you're still working on this PR, or are you done?

**Comment by steven2249** [comment]
@sckott finished with this PR

**Comment by sckott** [comment]
@FranzKrah any thoughts on this PR?

**Comment by FranzKrah** [comment]
@sckott <https://github.com/sckott> nope! go ahead!

**Pull request merged**
